### ISSUE TITLE
请求增加教程文章

### ISSUE THREAD

**Issue by woodchen-ink** [webp-sh/docs.webp.sh#3]
文章链接: https://q58.org/questions/D1h3

请考虑添加到Related Articles [#](https://docs.webp.sh/related_articles/#related-articles), 谢谢

**Comment by n0vad3v** [comment]
感谢！已经加入~
https://github.com/webp-sh/docs.webp.sh/commit/0d54cb4f2f13cf3e9aa178085dcb84465362a1fd
